USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WINDROSE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS WINDROSE_DB;

CREATE SCHEMA IF NOT EXISTS WINDROSE_DB.WEATHER;

USE WAREHOUSE WINDROSE_WH;
USE DATABASE WINDROSE_DB;
USE SCHEMA WEATHER;