USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS windrose_s3_integration
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://<S3_BUCKET_NAME>/<S3_PREFIX>/'
    );

DESC INTEGRATION windrose_s3_integration;

GRANT USAGE
ON INTEGRATION windrose_s3_integration
TO ROLE SYSADMIN;

SHOW GRANTS
ON INTEGRATION windrose_s3_integration;

USE ROLE SYSADMIN;